### ISSUE TITLE
panic: qtls.ClientHelloInfo doesn't match

### ISSUE THREAD

**Issue by hongyi-zhao** [AdguardTeam/dnsproxy#120] opened 2021-01-12 23:58 UTC
On Ubuntu 20.10, self-compiled dnsproxy git master version fails to run. See the following for detailed info:
```
$ git log -1
commit 662b1052c36b71c9e6d7f314313cfdde9da0325a (HEAD -> master, tag: v0.33.7, origin/master, origin/HEAD)
Merge: 2b7984a e760fed
Author: Ainar Garipov <a.garipov@adguard.com>
Date:   Thu Dec 17 17:23:22 2020 +0300

    Pull request: proxy: fix panic when logging empty results
    
    Merge in DNS/dnsproxy from fix-panic to master
    
    * commit 'e760fedbd50320068cbeaebc2666bc02253b4830':
      proxy: fix panic when logging empty results

$ go build -mod=vendor

$ ./dnsproxy -h
panic: qtls.ClientHelloInfo doesn't match

goroutine 1 [running]:
github.com/marten-seemann/qtls-go1-15.init.0()
	/home/werner/Public/anti-gfw/dns/dnsproxy/dnsproxy.git/vendor/github.com/marten-seemann/qtls-go1-15/unsafe.go:20 +0x1e5
```
Regards,
HY

**Comment by ainar-g** [comment] 2021-01-13 09:37
Hi, thanks for reporting.  I can't reproduce that on my Ubuntu 20.04, will try on a 20.10 vm a bit later.  In the meantime, can you please tell us:

1.  What is your CPU architecture?
1.  What is your Go version (`go version`)?
1.  Does building with `CGO_ENABLED=0` fix this?

Thanks!

**Comment by hongyi-zhao** [comment] 2021-01-13 09:55
>     1. What is your CPU architecture?

```
$ inxi -Cxxx
CPU:       Topology: 2x 22-Core model: Intel Xeon E5-2699 v4 bits: 64 type: MT MCP SMP arch: Broadwell rev: 1 
           L2 cache: 110.0 MiB 
           flags: avx avx2 lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 387275 
           Speed: 1200 MHz min/max: 1200/3600 MHz Core speeds (MHz): 1: 1532 2: 1394 3: 1202 4: 1200 5: 1201 6: 1202 
           7: 1202 8: 1201 9: 1202 10: 1401 11: 1694 12: 1204 13: 1202 14: 1918 15: 1428 16: 1202 17: 1202 18: 1202 
           19: 1202 20: 1202 21: 1202 22: 1200 23: 1202 24: 1202 25: 1202 26: 1202 27: 1203 28: 1202 29: 1202 30: 1203 
           31: 1202 32: 1202 33: 1202 34: 1202 35: 1203 36: 1704 37: 2201 38: 2201 39: 1201 40: 1442 41: 1317 42: 1200 
           43: 1201 44: 1200 45: 1201 46: 1202 47: 1201 48: 1200 49: 1201 50: 1200 51: 1201 52: 1201 53: 1201 54: 1200 
           55: 1201 56: 1201 57: 1203 58: 1201 59: 1401 60: 1678 61: 1200 62: 1985 63: 1461 64: 1201 65: 1200 66: 1201 
           67: 1200 68: 1203 69: 1201 70: 1201 71: 1201 72: 1201 73: 1201 74: 1200 75: 1200 76: 1201 77: 1200 78: 1201 
           79: 1202 80: 1201 81: 1200 82: 1201 83: 1200 84: 1797 85: 2200 86: 2200 87: 1200 88: 1203 
```
 
>     2. What is your Go version (`go version`)?
 
```
$ go version
go version devel +f7342596da Sat Nov 21 07:37:02 2020 +0000 linux/amd64

```
>     3. Does building with `CGO_ENABLED=0` fix this?

```
$ CGO_ENABLED=0 go build -mod=vendor
$ ./dnsproxy -h
panic: qtls.ClientHelloInfo doesn't match

goroutine 1 [running]:
github.com/marten-seemann/qtls-go1-15.init.0()
	/home/werner/Public/anti-gfw/dns/dnsproxy/dnsproxy.git/vendor/github.com/marten-seemann/qtls-go1-15/unsafe.go:20 +0x1e5
```

**Comment by ainar-g** [comment] 2021-01-13 09:58
Thanks for the info.  Your Go installation seems to be an outdated development version.  Can you check if building with a release version of Go, for example Go 1.15.6, fixes the issue for you?

**Comment by hongyi-zhao** [comment] 2021-01-13 11:37
I confirm that this problem doesn't appear for the latest git master version of go:
```
$ go version
go version devel +ba76567bc2 Tue Jan 12 21:39:59 2021 +0000 linux/amd64

$ go build -mod=vendor

$ ./dnsproxy -h
Usage:
  dnsproxy [OPTIONS]

Application Options:
  -v, --verbose          Verbose output (optional)
  -o, --output=          Path to the log file. If not set, write to stdout.
  -l, --listen=          Listening addresses (default: 0.0.0.0)
  -p, --port=            Listening ports. Zero value disables TCP and UDP listeners (default: 53)
  -h, --https-port=      Listening ports for DNS-over-HTTPS
  -t, --tls-port=        Listening ports for DNS-over-TLS
  -q, --quic-port=       Listening ports for DNS-over-QUIC
  -y, --dnscrypt-port=   Listening ports for DNSCrypt
  -c, --tls-crt=         Path to a file with the certificate chain
  -k, --tls-key=         Path to a file with the private key
  -g, --dnscrypt-config= Path to a file with DNSCrypt configuration. You can generate one using
                         https://github.com/ameshkov/dnscrypt
  -u, --upstream=        An upstream to be used (can be specified multiple times)
  -b, --bootstrap=       Bootstrap DNS for DoH and DoT, can be specified multiple times (default: 8.8.8.8:53)
  -f, --fallback=        Fallback resolvers to use when regular ones are unavailable, can be specified
                         multiple times
      --all-servers      If specified, parallel queries to all configured upstream servers are enabled
      --fastest-addr     Respond to A or AAAA requests only with the fastest IP address
      --cache            If specified, DNS cache is enabled
      --cache-size=      Cache size (in bytes). Default: 64k
      --cache-min-ttl=   Minimum TTL value for DNS entries, in seconds. Capped at 3600. Artificially
                         extending TTLs should only be done with careful consideration.
      --cache-max-ttl=   Maximum TTL value for DNS entries, in seconds.
  -r, --ratelimit=       Ratelimit (requests per second) (default: 0)
      --refuse-any       If specified, refuse ANY requests
      --edns             Use EDNS Client Subnet extension
      --edns-addr=       Send EDNS Client Address
      --ipv6-disabled    If specified, all AAAA requests will be replied with NoError RCode and empty answer
      --bogus-nxdomain=  Transform responses that contain at least one of the given IP addresses into
                         NXDOMAIN. Can be specified multiple times.
      --version          Prints the program version

Help Options:
  -h, --help             Show this help message
```

**Comment by ainar-g** [comment] 2021-01-13 11:46
I guess it's just an issue with that particular development version of Go.  In general, we don't support development versions of Go, so please use a release version when building `dnsproxy`.  I'm going to close this issue for now.

**Closed by ainar-g** 2021-01-13 11:46 UTC
Labels: bug
