### ISSUE TITLE
是否能写个docker 的dnsproxy？

### ISSUE THREAD

**Issue by Potterli20** [AdguardTeam/dnsproxy#205] opened 2022-02-13 20:49 UTC
如题

**Comment by Potterli20** [comment] 2022-02-13 21:20
能用systemctl 就行了
因为我不会去写，希望你们帮我去写一个，也是其他用户想用的

**Comment by Potterli20** [comment] 2022-02-19 16:56
https://github.com/AdguardTeam/AdGuardHome/discussions/4305

**Comment by ameshkov** [comment] 2022-02-20 09:44
Closing this as a duplicate of #208, I've also responded there.

**Closed by ameshkov** 2022-02-20 09:44 UTC
Labels: duplicate
