### ISSUE TITLE
System DNS is incorrectly used for bootstrapping upstream host names

### ISSUE THREAD

**Issue by agneevX** [AdguardTeam/dnsproxy#361] opened 2023-10-31 14:23 UTC
The README states:

```
 -b, --bootstrap=             Bootstrap DNS for DoH and DoT, can be specified multiple times (default: 8.8.8.8:53)
```

If this parameter is not specified, it seems that system DNS is used instead:

![Screenshot](https://github.com/AdguardTeam/dnsproxy/assets/19761269/2cf984da-046b-41f5-b240-77d42e59ae0d)

**Comment by EugeneOne1** [comment] 2023-10-31 14:34
@agneevX, hello and thanks for the report.  The default Go's built-in resolver is indeed used when the bootstraps aren't specified, this is an intended behavior.  The address `127.0.0.11` actually looks like the Docker's default system resolver which unfortunately is capable to misbehave, AFAIK.

**Comment by EugeneOne1** [comment] 2023-11-01 12:35
@agneevX, ah, I see.  This is false indeed, we'll fix the docs ASAP.

**Comment by EugeneOne1** [comment] 2023-11-01 16:22
@agneevX, should be fixed as per master.

**Closed by EugeneOne1** 2023-11-01 16:22 UTC
Labels: documentation
