### ISSUE TITLE
Request: A way to install dnsproxy as a Windows service.

### ISSUE THREAD

**Issue by phantomcraft** [AdguardTeam/dnsproxy#174] opened 2021-10-10 02:08 UTC
I tried to install by hand on my Windows installation by using NSSM: https://nssm.cc/usage

But the service doesn't start.

Can you implement support for installation as a Windows service?

**Comment by ameshkov** [comment] 2021-10-10 15:28
Duplicate of https://github.com/AdguardTeam/dnsproxy/issues/39

Currently, we don't have time to do that, but if someone can contribute this (the way to do is described there), we'll be happy to accept the contribution.

**Closed by ameshkov** 2021-10-10 15:28 UTC
Labels: duplicate

**Comment by Owyn** [comment] 2021-10-13 13:38
For some reason `sc.exe create` doesn't work to make dnsproxy into a win service and currently requires wrappers like NSSM
