### ISSUE TITLE
unpacking quic packet: dns: bad rdata

### ISSUE THREAD

**Issue by thb007** [AdguardTeam/dnsproxy#241] opened 2022-06-07 13:12 UTC
```
Jun  7 21:08:24 dnsproxy[786]: 2022/06/07 21:08:24 [error] unpacking quic packet: dns: bad rdata
Jun  7 21:08:24 dnsproxy[786]: 2022/06/07 21:08:24 [info] got error when accepting a new QUIC stream: Application error 0x2
Jun  7 21:08:36 dnsproxy[786]: 2022/06/07 21:08:36 [error] unpacking quic packet: dns: bad rdata
Jun  7 21:08:36 dnsproxy[786]: 2022/06/07 21:08:36 [info] got error when accepting a new QUIC stream: Application error 0x2
Jun  7 21:08:50 dnsproxy[786]: 2022/06/07 21:08:50 [error] unpacking quic packet: dns: bad rdata
Jun  7 21:08:50 dnsproxy[786]: 2022/06/07 21:08:50 [error] unpacking quic packet: dns: bad rdata
Jun  7 21:08:50 dnsproxy[786]: 2022/06/07 21:08:50 [error] unpacking quic packet: dns: bad rdata
Jun  7 21:08:50 dnsproxy[786]: 2022/06/07 21:08:50 [error] unpacking quic packet: dns: bad rdata
Jun  7 21:08:50 dnsproxy[786]: 2022/06/07 21:08:50 [info] got error when accepting a new QUIC stream: Application error 0x2
Jun  7 21:09:04 dnsproxy[786]: 2022/06/07 21:09:04 [error] unpacking quic packet: dns: bad rdata
Jun  7 21:09:04 dnsproxy[786]: 2022/06/07 21:09:04 [error] unpacking quic packet: dns: bad rdata
Jun  7 21:09:04 dnsproxy[786]: 2022/06/07 21:09:04 [info] got error when accepting a new QUIC stream: Application error 0x2
Jun  7 21:09:04 dnsproxy[786]: 2022/06/07 21:09:04 [error] unpacking quic packet: dns: bad rdata
Jun  7 21:09:04 dnsproxy[786]: 2022/06/07 21:09:04 [error] unpacking quic packet: dns: bad rdata
Jun  7 21:09:04 dnsproxy[786]: 2022/06/07 21:09:04 [error] unpacking quic packet: dns: bad rdata
Jun  7 21:09:04 dnsproxy[786]: 2022/06/07 21:09:04 [info] got error when accepting a new QUIC stream: Application error 0x2
Jun  7 21:09:08 dnsproxy[786]: 2022/06/07 21:09:08 [error] unpacking quic packet: dns: bad rdata
Jun  7 21:09:08 dnsproxy[786]: 2022/06/07 21:09:08 [error] unpacking quic packet: dns: bad rdata
Jun  7 21:09:08 dnsproxy[786]: 2022/06/07 21:09:08 [info] got error when accepting a new QUIC stream: Application error 0x2

```

**Comment by ameshkov** [comment] 2022-06-07 14:21
Well, it looks as if the DNS message is corrupted.

Where it comes from? Ideally, we need to see the original DNS message.

**Comment by thb007** [comment] 2022-06-08 12:17
> Well, it looks as if the DNS message is corrupted.
> 
> Where it comes from? Ideally, we need to see the original DNS message.

I don't know from where I need to enable logging

**Comment by thb007** [comment] 2022-06-08 12:33
```
2022/06/08 20:30:04 [info] Stopping the DNS proxy server
2022/06/08 20:30:04 [info] Stopped the DNS proxy server
2022/06/08 20:30:04 [info] Starting dnsproxy v0.42.4
2022/06/08 20:30:04 [info] Fallback 0 is 127.0.0.1:5300
2022/06/08 20:30:04 [info] Starting the DNS proxy server
2022/06/08 20:30:04 [info] Cache TTL override is enabled. Min=60, Max=120
2022/06/08 20:30:04 [info] DNS cache is enabled
2022/06/08 20:30:04 [info] Creating the UDP server socket
2022/06/08 20:30:04 [info] Listening to udp://[::]:5312
2022/06/08 20:30:04 [info] Creating a TCP server socket
2022/06/08 20:30:04 [info] Listening to tcp://[::]:5312
2022/06/08 20:30:04 [info] Creating a QUIC listener
2022/06/08 20:30:04 [info] Listening to quic://[::]:8053
2022/06/08 20:30:04 [info] Entering the tcp listener loop on [::]:5312
2022/06/08 20:30:04 [info] Entering the UDP listener loop on [::]:5312
2022/06/08 20:30:04 [info] Entering the DNS-over-QUIC listener loop on [::]:8053
2022/06/08 20:30:11 [error] unpacking quic packet: dns: bad rdata
2022/06/08 20:30:11 [info] got error when accepting a new QUIC stream: Application error 0x2
2022/06/08 20:30:38 [error] unpacking quic packet: dns: bad rdata
2022/06/08 20:30:38 [info] got error when accepting a new QUIC stream: Application error 0x2
2022/06/08 20:30:49 [error] unpacking quic packet: dns: bad rdata
2022/06/08 20:30:49 [info] got error when accepting a new QUIC stream: Application error 0x2
2022/06/08 20:31:00 [error] unpacking quic packet: dns: bad rdata
2022/06/08 20:31:00 [info] got error when accepting a new QUIC stream: Application error 0x2
2022/06/08 20:31:21 [error] unpacking quic packet: dns: bad rdata
2022/06/08 20:31:21 [info] got error when accepting a new QUIC stream: Application error 0x2
2022/06/08 20:31:52 [error] unpacking quic packet: dns: bad rdata
2022/06/08 20:31:52 [info] got error when accepting a new QUIC stream: Application error 0x2
2022/06/08 20:31:53 [error] unpacking quic packet: dns: bad rdata
2022/06/08 20:31:53 [info] got error when accepting a new QUIC stream: Application error 0x2
2022/06/08 20:32:32 [error] unpacking quic packet: dns: bad rdata
2022/06/08 20:32:32 [info] got error when accepting a new QUIC stream: Application error 0x2

```

**Comment by ameshkov** [comment] 2022-06-10 04:09
Let's close this for now since the information is not enough to make any conclusions. It may be some garbage connections or invalid clients. Nevertheless, if it does not influence how it works, this is just a line in the log and not a bug.

**Closed by ameshkov** 2022-06-10 04:09 UTC
